services:
  epickup:
    build:
      context: ./html
      dockerfile: ../Dockerfile
    ports:
      - "81:80"
    volumes:
      - ./html/:/usr/local/apache2/htdocs/
    container_name: epickup_website
